[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0
    adafruit/Adafruit PWM Servo Driver Library@^3.0
    hsaturn/TinyMqtt@^0.9
    sandeepmistry/LoRa@^0.8
build_flags =
    -DNODE_ID=\"hub-001\"
    -DWIFI_AP_SSID=\"SkyWatch-Hub\"
    -DWIFI_AP_PASS=\"phoenix2026\"
    -DARDUINO_USB_CDC_ON_BOOT=1
